lzc-sdk-version: '0.1'
name: lzcQuery
package: cloud.lazycat.app.lzcquery
version: 0.0.3
description: 数据获取工具
homepage: 
author: lazycat
min_os_version: 1.3.8
application:
  subdomain: lzc-query
  background_task: true
  multi_instance: true
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  public_path:
    - /
  routes:
    - /=http://nginx:80
services:
  server:
    image: crpi-kyqfans5x5yi0xen.cn-hangzhou.personal.cr.aliyuncs.com/lonng_image/lzc-query:0.0.1 
    binds:
      - /lzcapp/var/pics:/app/pics
      - /lzcapp/var/config:/app/config
    environment:
    - TOKEN={{ .U.token }}

  
  nginx:
    image: registry.lazycat.cloud/snyh1010/library/nginx:54809b2f36d0ff38
    setup_script: |
      cat <<'EOF' > /etc/nginx/conf.d/default.conf
      server {
          listen 80;
          server_name _;
      
          root /lzcapp/pkg/content/dist;
          index index.html;
      
          location / {
              try_files $uri /index.html;
          }
      
          location /api/ {
              proxy_pass http://server:8080/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
      EOF

